log_level: DEBUG  # DEBUG, INFO, WARNING, ERROR, etc.
drag:
  random_seed: 0
  num_peers: 10
  num_peer_attachments: 2
  query_confidence_threshold: 0.8
  num_query_neighbor: 2
  query_ttl: 6
  log_every_n_steps: 10
